// Short motivational pushes, deliberately unattributed: these are written
// for this app rather than quoted, so nothing here can be misattributed.
export const QUOTES: readonly string[] = [
  "Start with the smallest next step. Momentum does the rest.",
  "You don't need to feel ready. You just need to begin.",
  "One finished thing beats ten half-started ones.",
  "Do the hard thing first. The rest of the day gets lighter.",
  "Progress, not perfection. Ship the draft.",
  "Future you is counting on what you do in the next hour.",
  "Discipline is choosing what you want most over what you want now.",
  "Five focused minutes still count. Start the timer.",
  "Motivation follows action, not the other way around.",
  "Small steps every day beat big plans someday.",
  "The task you're avoiding is usually the one that matters.",
  "Don't wait for a better moment. Make this one count.",
  "Done is a decision. Make it today.",
  "You've handled hard days before. Handle this one.",
  "Focus on one thing. Finish it. Then pick the next.",
  "Consistency quietly outworks talent.",
  "Cross off the first task and watch the day change.",
  "Your goals don't care how you feel. Show up anyway.",
  "Every task completed is proof you can do the next one.",
  "Clear the small stuff so the big stuff has room.",
  "Stop planning the perfect start. Take an imperfect one.",
  "The only bad work session is the one that never began.",
  "Be the person who does it before they feel like it.",
  "Tired is temporary. Finished is forever.",
  "Make today's list shorter by doing, not by deleting.",
  "Ten minutes of effort now saves an hour of worry later.",
  "Protect your focus like it's your most valuable asset. It is.",
  "Nobody is coming to do it for you, and that's your power.",
  "Win the morning, and the day follows.",
  "Turn 'I should' into 'I did'.",
  "Hard work compounds. So does putting it off.",
  "You are one focused hour away from a better day.",
  "Break it down until it's too small to resist.",
  "Keep the streak alive. Just today, just this one.",
  "Effort is the only part of success you fully control.",
  "Say yes to the work that moves you forward.",
  "The best time to start was earlier. The next best is now.",
  "Quiet, steady work beats loud intentions.",
  "Finish what's in front of you before reaching for what's next.",
  "Today's discomfort is tomorrow's confidence.",
  "Get moving. Clarity comes while you work, not before.",
  "Pick one priority and give it your full attention.",
  "You're building something. Add a brick today.",
  "Excuses are heavy. Tasks are lighter once you start.",
  "Show up, do the work, repeat. That's the whole secret.",
  "A messy first attempt beats a perfect plan that never starts.",
  "Momentum is built one completed task at a time.",
  "Choose progress over comfort, just for today.",
  "The list won't shrink itself. Go get the first one.",
  "Keep going. You're closer than it feels.",
  "Do it for the version of you who'll be glad it's done.",
  "Rest is earned by finishing, so finish.",
  "Make it a day you're proud of by evening.",
  "Start before you're sure. Adjust as you go.",
  "Every expert once had an unchecked task list too.",
  "Trade one hour of distraction for one hour of progress.",
  "You don't have to do everything. Just the next thing.",
  "Courage is opening the task you've been dodging.",
  "The work is waiting. So is the satisfaction of finishing it.",
  "Let today's effort be louder than yesterday's excuses.",
];

// Deterministic per local calendar day, so it stays the same all day and
// changes at the user's own midnight (not UTC).
export function quoteForDate(date: Date = new Date()): string {
  const dayNumber = Math.floor(
    Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / 86_400_000,
  );
  return QUOTES[((dayNumber % QUOTES.length) + QUOTES.length) % QUOTES.length];
}
